BEGIN TRANSACTION;
CREATE TABLE "RATINGS" (
	`_id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`Rating`	NUMERIC
);
INSERT INTO `RATINGS` (_id,Rating) VALUES (1,NULL);
INSERT INTO `RATINGS` (_id,Rating) VALUES (2,NULL);
INSERT INTO `RATINGS` (_id,Rating) VALUES (3,NULL);
INSERT INTO `RATINGS` (_id,Rating) VALUES (4,NULL);
INSERT INTO `RATINGS` (_id,Rating) VALUES (5,NULL);
INSERT INTO `RATINGS` (_id,Rating) VALUES (6,NULL);
INSERT INTO `RATINGS` (_id,Rating) VALUES (7,NULL);
INSERT INTO `RATINGS` (_id,Rating) VALUES (8,NULL);
INSERT INTO `RATINGS` (_id,Rating) VALUES (9,NULL);
INSERT INTO `RATINGS` (_id,Rating) VALUES (10,NULL);
COMMIT;
